### ISSUE TITLE
The integration stop working

### ISSUE THREAD

**Issue by Kathou99** [martinarva/dynamic_energy_cost#40]
**Describe the bug**

**To Reproduce**
1. I just added the entity in W and when I reboot HA I got this error:

```
Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/config/custom_components/dynamic_energy_cost/power_based_sensors.py", line 208, in _reset_meter
    self.schedule_next_reset()
  File "/config/custom_components/dynamic_energy_cost/power_based_sensors.py", line 194, in schedule_next_reset
    self.hass.async_create_task(self.hass.async_remove_job(self._reset_timer))
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'HomeAssistant' object has no attribute 'async_remove_job'. Did you mean: 'async_run_job'?

```
**Expected behavior**

To work

**Desktop (please complete the following information):**
 - OS: window 11 (but it s HA has the problem)
 - Browser Brave
 - Version 2024.7.3

**Comment by Kathou99** [comment]
I may have found the issue, I post the fix in a full post request with other fix

**Comment by Kathou99** [comment]
#41 This pull fixed with issue
