### ISSUE TITLE
NameError: name 'exceptions' is not defined (config_flow.py, line 37)

### ISSUE THREAD

**Issue by lordyavin** [martinarva/dynamic_energy_cost#47]
**Describe the bug**
I tried to add the integration with energy and power sensor. This failed with an unknow error. Sorry did not take a screenshot of the error dialog. After I removed the power sensor I was able to finish the setup.

**To Reproduce**
1. Go to 'Settings>Devices&Services'
2. Click on 'Add Integration'
3. Scroll down to 'Dynamic Energy Costs'
4. Configure energy and power sensor
5. See the error

**Expected behavior**
The dialog stated that the power sensor is optional if the energy sensor is given. So I expect that configuring both is possible.

**Logs**
```
2024-11-17 22:20:38.906 WARNING (MainThread) [custom_components.dynamic_energy_cost.config_flow] Both power and energy sensors were provided.
2024-11-17 22:20:38.906 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 477, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 567, in _handle
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 83, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 86, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 81, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 222, in post
    return await super().post(request, flow_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 74, in wrapper
    return await method(view, request, data, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 122, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 367, in async_configure
    result = await self._async_configure(flow_id, user_input)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 414, in _async_configure
    result = await self._async_handle_step(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 517, in _async_handle_step
    result: _FlowResultT = await getattr(flow, method)(user_input)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dynamic_energy_cost/config_flow.py", line 37, in async_step_user
    raise exceptions.Invalid("Please enter only one type of sensor (power or energy).")
          ^^^^^^^^^^
NameError: name 'exceptions' is not defined. Did you mean: 'Exception'?
2024-11-17 22:20:49.860 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'dynamic_energy_cost' calls async_forward_entry_setup for integration, dynamic_energy_cost with title: Dynamic Energy Cost and entry_id: 01JCXZZWNWV0V5SRRAVPTP4RFQ, which is deprecated and will stop working in Home Assistant 2025.6, await async_forward_entry_setups instead at custom_components/dynamic_energy_cost/__init__.py, line 21: setup_result = await hass.config_entries.async_forward_entry_setup(entry, 'sensor'), please create a bug report at https://github.com/martinarva/dynamic_energy_cost/issues/
2024-11-17 22:20:49.922 ERROR (MainThread) [custom_components.dynamic_energy_cost.energy_based_sensors] Failed to update energy costs due to an error: No entity id specified for entity Ev Power Meter Total Active Daily Energy Cost
Traceback (most recent call last):
  File "/config/custom_components/dynamic_energy_cost/energy_based_sensors.py", line 200, in async_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1004, in async_write_ha_state
    self._async_verify_state_writable()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 987, in _async_verify_state_writable
    raise NoEntitySpecifiedError(
homeassistant.exceptions.NoEntitySpecifiedError: No entity id specified for entity Ev Power Meter Total Active Daily Energy Cost
2024-11-17 22:20:49.925 ERROR (MainThread) [custom_components.dynamic_energy_cost.energy_based_sensors] Failed to update energy costs due to an error: No entity id specified for entity Ev Power Meter Total Active Weekly Energy Cost
Traceback (most recent call last):
  File "/config/custom_components/dynamic_energy_cost/energy_based_sensors.py", line 200, in async_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1004, in async_write_ha_state
    self._async_verify_state_writable()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 987, in _async_verify_state_writable
    raise NoEntitySpecifiedError(
homeassistant.exceptions.NoEntitySpecifiedError: No entity id specified for entity Ev Power Meter Total Active Weekly Energy Cost
2024-11-17 22:20:49.927 ERROR (MainThread) [custom_components.dynamic_energy_cost.energy_based_sensors] Failed to update energy costs due to an error: No entity id specified for entity Ev Power Meter Total Active Monthly Energy Cost
Traceback (most recent call last):
  File "/config/custom_components/dynamic_energy_cost/energy_based_sensors.py", line 200, in async_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1004, in async_write_ha_state
    self._async_verify_state_writable()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 987, in _async_verify_state_writable
    raise NoEntitySpecifiedError(
homeassistant.exceptions.NoEntitySpecifiedError: No entity id specified for entity Ev Power Meter Total Active Monthly Energy Cost
2024-11-17 22:20:49.959 ERROR (MainThread) [custom_components.dynamic_energy_cost.energy_based_sensors] Failed to update energy costs due to an error: No entity id specified for entity Ev Power Meter Total Active Yearly Energy Cost
Traceback (most recent call last):
  File "/config/custom_components/dynamic_energy_cost/energy_based_sensors.py", line 200, in async_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1004, in async_write_ha_state
    self._async_verify_state_writable()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 987, in _async_verify_state_writable
    raise NoEntitySpecifiedError(
homeassistant.exceptions.NoEntitySpecifiedError: No entity id specified for entity Ev Power Meter Total Active Yearly Energy Cost
2024-11-17 22:20:55.528 ERROR (MainThread) [homeassistant.helpers.service] Failed to load integration: dynamic_energy_cost
NoneType: None
```

**Desktop (please complete the following information):**
 - OS: Windows10
 - Browser Firefox 132.0.2
 - Version 0.5.0

**Additional context**
Bot sensors are provided by a Shelly Pro 3EM

**Comment by lordyavin** [comment]
May be related with #46

**Comment by robinelfving** [comment]
This should be solved.
